FROM node:lts-alpine3.21 as builder

WORKDIR /app

COPY src src
COPY package.json package.json
COPY tsconfig.json tsconfig.json

RUN npm install

RUN npm run build

FROM node:lts-alpine3.21

RUN apk --no-cache add curl

WORKDIR /app

COPY --from=builder /app/dist /app/dist

COPY package.json package.json

RUN npm install --production

CMD npm run startprod